### ISSUE TITLE
Types of accepted files

### ISSUE THREAD

**Issue by erikanoms** [VIDA-NYU/reproserver#61]
3: Major Usability Problem
Adding a supported file type would be helpful for new user -both upload page and web capture page
<img width="424" alt="Screen Shot 2022-08-18 at 12 18 23" src="https://user-images.githubusercontent.com/94011156/185444837-601239a8-f932-46a3-b4c2-eda29ebd0223.png">
<img width="326" alt="Screen Shot 2022-08-18 at 12 17 02" src="https://user-images.githubusercontent.com/94011156/185444887-7935d71b-73ae-4870-9cb7-1d3e0a43b929.png">
s

**Comment by remram44** [comment]
Fixed by 4748ad4a (master) and 6adca321 (web)

**Comment by VickyRampin** [comment]
This works! I tried uploading a png file and got taken to an error page where it asks (is it an RPZ?). Just a UX note, is there anyway to do validation on the same page? Like if I try to upload anything except an RPZ, it stops me from proceeding with the form submission? No worries if not, this is fine, but it might be more in-line with how other forms on the web work.

**Comment by remram44** [comment]
It should have done that. You should only see .rpz files in the file browser dialog, unless you go in the file type dropdown and change it:

![screenshot](https://user-images.githubusercontent.com/426784/192591084-515f6f95-408a-4a4b-8b68-375025861f01.png)

**Comment by remram44** [comment]
It seems that she did change the filter.
