### ISSUE TITLE
Upload page: Order

### ISSUE THREAD

**Issue by erikanoms** [VIDA-NYU/reproserver#66]
2: Minor Usability Problem
I would change the order of the upload page to allow users to learn how to use it first
1. How to use this site
2. Examples
3. Select a package
<img width="539" alt="Screen Shot 2022-08-18 at 12 33 17" src="https://user-images.githubusercontent.com/94011156/185447581-1142d396-ebbe-4491-94b3-b5a340e3b322.png">
 to upload

**Comment by remram44** [comment]
Fixed by c8330a53
