### ISSUE TITLE
Web capture page: text description

### ISSUE THREAD

**Issue by erikanoms** [VIDA-NYU/reproserver#72]
3: Major Usability Problem
Suggestion for text description on web capture page:

> Select your own .rpz file, or try using one of the examples from the ReproZip-Examples repository, and click the "Upload" button!
From there, you can set parameters and (optionally) upload your own inputs, and then reproduce the work by clicking the "Run" button. You can then see the log and output files from the research, which you can view or download to your machine. You can also share the lin
<img width="686" alt="Screen Shot 2022-08-18 at 12 46 20" src="https://user-images.githubusercontent.com/94011156/185450135-197023e1-365e-40bb-9d48-ba6261e879db.png">
k for other people to reproduce your research.

**Comment by remram44** [comment]
![screenshot](https://user-images.githubusercontent.com/426784/229558859-5e4dce4d-d992-43e8-9917-396a5947fc0d.png)

> If this RPZ is a web application, you can use ReproServer to capture the remote assets that are referenced by it (CSS, JS, etc). This will allow the application to keep working correctly in web browsers if those remote sources go away.
